# ----------- CONFIGURABLE START -----------
title:            "whikwon's blog"
description:      ""
url:              https://whikwon.github.io # Site url, without a slash at the end.
signoff:          "whikwon" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            true # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink: /posts/:title
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: "default"
      comments: true

socialmedia:
  facebook: whi.kwon

disqus_shortname: whikwon-disqus-com-1
